// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDb3Qzzpuqp_TQgd6sIFg_iEQgy1atbE',
    appId: '1:342958754406:web:47973129314a68a390bba7',
    messagingSenderId: '342958754406',
    projectId: 'plant-c85af',
    authDomain: 'plant-c85af.firebaseapp.com',
    storageBucket: 'plant-c85af.firebasestorage.app',
    measurementId: 'G-46V9YB03EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjaxALSffEoebC1kraqRaR546bOq5dx2Q',
    appId: '1:342958754406:android:10153c096a6b7e6190bba7',
    messagingSenderId: '342958754406',
    projectId: 'plant-c85af',
    storageBucket: 'plant-c85af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtZzrXYxEEwT9YZu-l-fdIluVwRBscys',
    appId: '1:342958754406:ios:a723aa3251a0a65c90bba7',
    messagingSenderId: '342958754406',
    projectId: 'plant-c85af',
    storageBucket: 'plant-c85af.firebasestorage.app',
    iosBundleId: 'com.example.plant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtZzrXYxEEwT9YZu-l-fdIluVwRBscys',
    appId: '1:342958754406:ios:a723aa3251a0a65c90bba7',
    messagingSenderId: '342958754406',
    projectId: 'plant-c85af',
    storageBucket: 'plant-c85af.firebasestorage.app',
    iosBundleId: 'com.example.plant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmDb3Qzzpuqp_TQgd6sIFg_iEQgy1atbE',
    appId: '1:342958754406:web:bdee0d7dd8a934f590bba7',
    messagingSenderId: '342958754406',
    projectId: 'plant-c85af',
    authDomain: 'plant-c85af.firebaseapp.com',
    storageBucket: 'plant-c85af.firebasestorage.app',
    measurementId: 'G-0VM7Y670VZ',
  );
}
